2025-10-05 12:52:51,977 : INFO : root : Loading config.
2025-10-05 12:52:51,981 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2025-10-05 12:52:51,982 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\bad76953a596b8c99f832e0e98026c3b.mpf_cache
2025-10-05 12:52:51,991 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\richa\ttp5\config\config_ball_devices.yaml
2025-10-05 12:52:51,991 : INFO : ConfigProcessor : Loading config from file C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\mpfconfig.yaml.
2025-10-05 12:52:52,005 : INFO : ConfigProcessor : Loading config: C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\mpfconfig.yaml
2025-10-05 12:52:52,006 : INFO : ConfigProcessor : Loading config from file C:\Users\richa\ttp5\config\config.yaml.
2025-10-05 12:52:52,007 : INFO : ConfigProcessor : Loading config: C:\Users\richa\ttp5\config\config.yaml
2025-10-05 12:52:52,015 : INFO : ConfigProcessor : Loading config: C:\Users\richa\ttp5\config\config_ball_devices.yaml
2025-10-05 12:52:52,017 : INFO : ConfigProcessor : Loading config: C:\Users\richa\ttp5\config\config_coils.yaml
2025-10-05 12:52:52,018 : INFO : ConfigProcessor : Loading config: C:\Users\richa\ttp5\config\config_flippers.yaml
2025-10-05 12:52:52,022 : INFO : ConfigProcessor : Loading config: C:\Users\richa\ttp5\config\config_switches.yaml
2025-10-05 12:52:52,025 : INFO : ConfigProcessor : Loading config: C:\Users\richa\ttp5\config\config_lights.yaml
2025-10-05 12:52:52,027 : INFO : ConfigProcessor : Config file cache created: C:\Users\richa\AppData\Local\Temp\bad76953a596b8c99f832e0e98026c3b.mpf_cache
2025-10-05 12:52:52,112 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\77a998d318c788df5647a1900cedfc56.mpf_cache
2025-10-05 12:52:52,113 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\9c8dea79ca4d15ee886340e992e8cb9d.mpf_cache
2025-10-05 12:52:52,114 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\8ddee2e87a4f178751335e99da00e9c4.mpf_cache
2025-10-05 12:52:52,115 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\16d594341c3fbe91b1b6d496c05a6fb0.mpf_cache
2025-10-05 12:52:52,116 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\9ea1b14cb2b1cce5e8bf981a1ff8cfc5.mpf_cache
2025-10-05 12:52:52,117 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\6cbce11faef0ddcfeddb2a5b8dbeb4ae.mpf_cache
2025-10-05 12:52:52,117 : INFO : Machine : Mission Pinball Framework Core Engine v0.57.0.dev39
2025-10-05 12:52:52,117 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2025-10-05-12-52-51-mpf-DESKTOP-RK7BE5M.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'virtual', 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2025-10-05 12:52:52,117 : INFO : Machine : MPF path: C:\Users\richa\mpfvirtual4\lib\site-packages\mpf
2025-10-05 12:52:52,117 : INFO : Machine : Machine path: C:\Users\richa\ttp5
2025-10-05 12:52:52,117 : INFO : Machine : Platform: win32
2025-10-05 12:52:52,117 : INFO : Machine : Python executable location: C:\Users\richa\mpfvirtual4\Scripts\python.exe
2025-10-05 12:52:52,117 : INFO : Machine : Python version: 3.9.13 (64-bit)
2025-10-05 12:52:52,120 : INFO : Machine : Initializing MPF...
2025-10-05 12:52:52,485 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2025-10-05 12:52:52,539 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2025-10-05 12:52:52,539 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 17500, 'prev_value': None, 'change': True}
2025-10-05 12:52:52,539 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.57.0.dev39', 'prev_value': None, 'change': True}
2025-10-05 12:52:52,539 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.57.0.dev39, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2025-10-05 12:52:52,539 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.9.13', 'prev_value': None, 'change': True}
2025-10-05 12:52:52,549 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.19045-SP0', 'prev_value': None, 'change': True}
2025-10-05 12:52:52,549 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2025-10-05 12:52:52,549 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2025-10-05 12:52:52,549 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.19045', 'prev_value': None, 'change': True}
2025-10-05 12:52:52,549 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2025-10-05 12:52:52,549 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2025-10-05 12:52:52,586 : ERROR : asyncio : Task exception was never retrieved
future: <Task finished name='Task-136' coro=<SystemWideDevice.device_added_system_wide() done, defined at C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\system_wide_device.py:15> exception=ConfigFileError('Configuration error in bd_left_scoop ball device. Device needs an eject_coil, a hold_coil, or "mechanical_eject: True"')>
Traceback (most recent call last):
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\system_wide_device.py", line 17, in device_added_system_wide
    await self._initialize()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\devices\ball_device\ball_device.py", line 90, in _initialize
    self._configure_targets()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\devices\ball_device\ball_device.py", line 365, in _configure_targets
    self._validate_config()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\devices\ball_device\ball_device.py", line 310, in _validate_config
    self.raise_config_error('Configuration error in {} ball device. '
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\logging.py", line 174, in raise_config_error
    raise ConfigFileError(msg, error_no, self.log.name if self.log else "", context, self._url_base) \
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ball_device.bd_left_scoop: Configuration error in bd_left_scoop ball device. Device needs an eject_coil, a hold_coil, or "mechanical_eject: True" Error Code: CFE-ball_device-4 (https://missionpinball.org/logs)
2025-10-05 12:52:52,614 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2025-10-05 12:52:52,614 : INFO : Machine : Starting the main run loop.
2025-10-05 12:52:52,622 : INFO : Machine : Shutting down...
2025-10-05 12:52:52,623 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2025-10-05 12:52:52,623 : INFO : SwitchController : Found active switch: ('2', <Platform.Virtual>) <switch.s_trough1>
2025-10-05 12:52:52,624 : INFO : SwitchController : Found active switch: ('3', <Platform.Virtual>) <switch.s_trough2>
2025-10-05 12:52:52,624 : INFO : SwitchController : Found active switch: ('4', <Platform.Virtual>) <switch.s_trough3>
2025-10-05 12:52:52,625 : INFO : SwitchController : Found active switch: ('5', <Platform.Virtual>) <switch.s_trough4>
2025-10-05 12:52:52,625 : INFO : SwitchController : Found active switch: ('6', <Platform.Virtual>) <switch.s_trough5>
2025-10-05 12:52:52,626 : INFO : SwitchController : Found active switch: ('7', <Platform.Virtual>) <switch.s_trough6>
2025-10-05 12:52:52,629 : INFO : EventManager : Event: ======'bcp_connection_attempt'====== Args={'name': 'local_display', 'host': 'localhost', 'port': 5050}
2025-10-05 12:52:52,631 : ERROR : asyncio : Exception in callback EventManager.process_event_queue()
handle: <Handle EventManager.process_event_queue()>
Traceback (most recent call last):
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 751, in _run_handlers
    result = handler.callback(**merged_kwargs)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\text_ui.py", line 455, in _bcp_connection_attempt
    self._pending_bcp_connection = PopUpDialog(self.screen,
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\asciimatics\widgets\popupdialog.py", line 44, in __init__
    string_len = wcswidth if screen.unicode_aware else len
AttributeError: 'NoneType' object has no attribute 'unicode_aware'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\richa\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 842, in process_event_queue
    self._process_event(event=event[0],
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 804, in _process_event
    result = self._run_handlers(event, ev_type, kwargs)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 753, in _run_handlers
    raise EventHandlerException(
mpf.core.events.EventHandlerException: Exception while processing RegisteredHandler(callback=<bound method TextUi._bcp_connection_attempt of <mpf.core.text_ui.TextUi object at 0x0000029D2C67F500>>, priority=1, kwargs={}, key=UUID('11dace72-1098-4c2d-878c-8abeb408654a'), condition=None, blocking_facility=None) for event bcp_connection_attempt. 'NoneType' object has no attribute 'unicode_aware'
2025-10-05 12:52:52,659 : INFO : BCPClientSocket : Connecting BCP to 'local_display' at localhost:5050...
2025-10-05 12:52:53,627 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\machine.py", line 788, in _run_loop
    raise self._exception['exception']
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\system_wide_device.py", line 17, in device_added_system_wide
    await self._initialize()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\devices\ball_device\ball_device.py", line 90, in _initialize
    self._configure_targets()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\devices\ball_device\ball_device.py", line 365, in _configure_targets
    self._validate_config()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\devices\ball_device\ball_device.py", line 310, in _validate_config
    self.raise_config_error('Configuration error in {} ball device. '
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\logging.py", line 174, in raise_config_error
    raise ConfigFileError(msg, error_no, self.log.name if self.log else "", context, self._url_base) \
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ball_device.bd_left_scoop: Configuration error in bd_left_scoop ball device. Device needs an eject_coil, a hold_coil, or "mechanical_eject: True" Error Code: CFE-ball_device-4 (https://missionpinball.org/logs)
2025-10-05 12:53:04,579 : ERROR : root : 
Traceback (most recent call last):
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\machine.py", line 788, in _run_loop
    raise self._exception['exception']
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\system_wide_device.py", line 17, in device_added_system_wide
    await self._initialize()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\devices\ball_device\ball_device.py", line 90, in _initialize
    self._configure_targets()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\devices\ball_device\ball_device.py", line 365, in _configure_targets
    self._validate_config()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\devices\ball_device\ball_device.py", line 310, in _validate_config
    self.raise_config_error('Configuration error in {} ball device. '
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\logging.py", line 174, in raise_config_error
    raise ConfigFileError(msg, error_no, self.log.name if self.log else "", context, self._url_base) \
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ball_device.bd_left_scoop: Configuration error in bd_left_scoop ball device. Device needs an eject_coil, a hold_coil, or "mechanical_eject: True" Error Code: CFE-ball_device-4 (https://missionpinball.org/logs)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\commands\game.py", line 236, in __init__
    self.machine.run()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\machine.py", line 684, in run
    self._run_loop()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\machine.py", line 791, in _run_loop
    report_crash(self._exception['exception'], "exception_during_run", self.config)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\crash_reporter.py", line 236, in report_crash
    response = input("Do you want to report the crash to the MPF team (yes/no/show)? ")
EOFError
