2025-10-03 18:28:43,721 : INFO : root : Loading config.
2025-10-03 18:28:43,726 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2025-10-03 18:28:43,726 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\bad76953a596b8c99f832e0e98026c3b.mpf_cache
2025-10-03 18:28:43,809 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\77a998d318c788df5647a1900cedfc56.mpf_cache
2025-10-03 18:28:43,810 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\9c8dea79ca4d15ee886340e992e8cb9d.mpf_cache
2025-10-03 18:28:43,811 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\8ddee2e87a4f178751335e99da00e9c4.mpf_cache
2025-10-03 18:28:43,812 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\16d594341c3fbe91b1b6d496c05a6fb0.mpf_cache
2025-10-03 18:28:43,813 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\richa\ttp5\modes\attract\shows\.\attract_light_show.yaml
2025-10-03 18:28:43,813 : INFO : ConfigProcessor : Loading config from file C:\Users\richa\ttp5\modes\attract\shows\.\attract_light_show.yaml.
2025-10-03 18:28:43,822 : INFO : ConfigProcessor : Loading config: C:\Users\richa\ttp5\modes\attract\shows\.\attract_light_show.yaml
2025-10-03 18:28:43,823 : INFO : ConfigProcessor : Config file cache created: C:\Users\richa\AppData\Local\Temp\9ea1b14cb2b1cce5e8bf981a1ff8cfc5.mpf_cache
2025-10-03 18:28:43,823 : INFO : Machine : Mission Pinball Framework Core Engine v0.57.0.dev39
2025-10-03 18:28:43,823 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2025-10-03-18-28-43-mpf-DESKTOP-RK7BE5M.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2025-10-03 18:28:43,823 : INFO : Machine : MPF path: C:\Users\richa\mpfvirtual4\lib\site-packages\mpf
2025-10-03 18:28:43,823 : INFO : Machine : Machine path: C:\Users\richa\ttp5
2025-10-03 18:28:43,823 : INFO : Machine : Platform: win32
2025-10-03 18:28:43,823 : INFO : Machine : Python executable location: C:\Users\richa\mpfvirtual4\Scripts\python.exe
2025-10-03 18:28:43,823 : INFO : Machine : Python version: 3.9.13 (64-bit)
2025-10-03 18:28:43,825 : INFO : Machine : Initializing MPF...
2025-10-03 18:28:44,236 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2025-10-03 18:28:44,288 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2025-10-03 18:28:44,289 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 14636, 'prev_value': None, 'change': True}
2025-10-03 18:28:44,289 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.57.0.dev39', 'prev_value': None, 'change': True}
2025-10-03 18:28:44,289 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.57.0.dev39, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2025-10-03 18:28:44,289 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.9.13', 'prev_value': None, 'change': True}
2025-10-03 18:28:44,298 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.19045-SP0', 'prev_value': None, 'change': True}
2025-10-03 18:28:44,298 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2025-10-03 18:28:44,299 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2025-10-03 18:28:44,299 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.19045', 'prev_value': None, 'change': True}
2025-10-03 18:28:44,299 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2025-10-03 18:28:44,299 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2025-10-03 18:28:44,315 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2025-10-03 18:28:44,315 : INFO : SwitchController : Found active switch: ('2', <Platform.SmartVirtual>) <switch.s_trough1>
2025-10-03 18:28:44,315 : INFO : SwitchController : Found active switch: ('3', <Platform.SmartVirtual>) <switch.s_trough2>
2025-10-03 18:28:44,315 : INFO : SwitchController : Found active switch: ('4', <Platform.SmartVirtual>) <switch.s_trough3>
2025-10-03 18:28:44,315 : INFO : SwitchController : Found active switch: ('5', <Platform.SmartVirtual>) <switch.s_trough4>
2025-10-03 18:28:44,315 : INFO : SwitchController : Found active switch: ('6', <Platform.SmartVirtual>) <switch.s_trough5>
2025-10-03 18:28:44,316 : INFO : SwitchController : Found active switch: ('7', <Platform.SmartVirtual>) <switch.s_trough6>
2025-10-03 18:28:44,319 : INFO : EventManager : Event: ======'bcp_connection_attempt'====== Args={'name': 'local_display', 'host': 'localhost', 'port': 5050}
2025-10-03 18:28:44,322 : INFO : BCPClientSocket : Connecting BCP to 'local_display' at localhost:5050...
2025-10-03 18:28:46,343 : INFO : BCPClientSocket : Connected BCP to 'local_display' localhost:5050
2025-10-03 18:28:46,344 : INFO : EventManager : Event: ======'bcp_clients_connected'====== Args={}
2025-10-03 18:28:46,686 : INFO : EventManager : Event: ======'machine_var_mc_version'====== Args={'value': 'MPF-MC v0.57.0.dev10', 'prev_value': None, 'change': True}
2025-10-03 18:28:46,686 : INFO : EventManager : Event: ======'machine_var_mc_extended_version'====== Args={'value': 'MPF-MC v0.57.0.dev10 (config_version=6, BCP v1.1,                      Requires MPF API compatibility v0.57.0.dev19 or newer)', 'prev_value': None, 'change': True}
2025-10-03 18:28:46,688 : INFO : ball_device.bd_trough : BCH: Initial count: 6
2025-10-03 18:28:46,745 : INFO : ball_device.bd_trough : State: idle
2025-10-03 18:28:46,746 : INFO : ball_device.bd_plunger : BCH: Initial count: 0
2025-10-03 18:28:46,746 : INFO : ball_device.bd_plunger : State: idle
2025-10-03 18:28:46,754 : INFO : EventManager : Event: ======'init_phase_3'====== Args={}
2025-10-03 18:28:46,756 : ERROR : asyncio : Exception in callback EventManager._queue_task_done(<Task finishe...t [\'l_I\']')>)
handle: <Handle EventManager._queue_task_done(<Task finishe...t [\'l_I\']')>)>
Traceback (most recent call last):
  File "C:\Users\richa\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 791, in _queue_task_done
    future.result()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 704, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\show_controller.py", line 53, in _load_shows
    self.machine.shows[show_name].load(show_config)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\assets\show.py", line 171, in load
    self._process_step_actions(step, actions)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\assets\show.py", line 201, in _process_step_actions
    raise e
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\assets\show.py", line 197, in _process_step_actions
    self.machine.show_controller.show_players[key].validate_config_entry(value, self.name)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\device_config_player.py", line 56, in validate_config_entry
    raise e
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\device_config_player.py", line 86, in _validate_config_item
    devices = self._expand_device(device)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\device_config_player.py", line 115, in _expand_device
    return self.raise_config_error(
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\logging.py", line 174, in raise_config_error
    raise ConfigFileError(msg, error_no, self.log.name if self.log else "", context, self._url_base) \
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in light_player: Show "attract_light_show" >> Failed to load config player attract_light_show:lights with settings {'l_I': 0, 'l_T': 'ff'} >> Could not find a lights device with name or tag l_I, from list ['l_I'] Error Code: CFE-light_player-101 (https://missionpinball.org/logs)
2025-10-03 18:28:46,759 : INFO : Machine : Starting the main run loop.
2025-10-03 18:28:46,760 : INFO : Machine : Shutting down...
2025-10-03 18:28:46,761 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2025-10-03 18:28:47,777 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\machine.py", line 788, in _run_loop
    raise self._exception['exception']
  File "C:\Users\richa\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 791, in _queue_task_done
    future.result()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 704, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\show_controller.py", line 53, in _load_shows
    self.machine.shows[show_name].load(show_config)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\assets\show.py", line 171, in load
    self._process_step_actions(step, actions)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\assets\show.py", line 201, in _process_step_actions
    raise e
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\assets\show.py", line 197, in _process_step_actions
    self.machine.show_controller.show_players[key].validate_config_entry(value, self.name)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\device_config_player.py", line 56, in validate_config_entry
    raise e
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\device_config_player.py", line 86, in _validate_config_item
    devices = self._expand_device(device)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\device_config_player.py", line 115, in _expand_device
    return self.raise_config_error(
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\logging.py", line 174, in raise_config_error
    raise ConfigFileError(msg, error_no, self.log.name if self.log else "", context, self._url_base) \
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in light_player: Show "attract_light_show" >> Failed to load config player attract_light_show:lights with settings {'l_I': 0, 'l_T': 'ff'} >> Could not find a lights device with name or tag l_I, from list ['l_I'] Error Code: CFE-light_player-101 (https://missionpinball.org/logs)
2025-10-03 18:28:51,120 : ERROR : root : 
Traceback (most recent call last):
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\machine.py", line 788, in _run_loop
    raise self._exception['exception']
  File "C:\Users\richa\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 791, in _queue_task_done
    future.result()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 704, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\show_controller.py", line 53, in _load_shows
    self.machine.shows[show_name].load(show_config)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\assets\show.py", line 171, in load
    self._process_step_actions(step, actions)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\assets\show.py", line 201, in _process_step_actions
    raise e
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\assets\show.py", line 197, in _process_step_actions
    self.machine.show_controller.show_players[key].validate_config_entry(value, self.name)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\device_config_player.py", line 56, in validate_config_entry
    raise e
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\device_config_player.py", line 86, in _validate_config_item
    devices = self._expand_device(device)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\device_config_player.py", line 115, in _expand_device
    return self.raise_config_error(
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\logging.py", line 174, in raise_config_error
    raise ConfigFileError(msg, error_no, self.log.name if self.log else "", context, self._url_base) \
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in light_player: Show "attract_light_show" >> Failed to load config player attract_light_show:lights with settings {'l_I': 0, 'l_T': 'ff'} >> Could not find a lights device with name or tag l_I, from list ['l_I'] Error Code: CFE-light_player-101 (https://missionpinball.org/logs)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\commands\game.py", line 236, in __init__
    self.machine.run()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\machine.py", line 684, in run
    self._run_loop()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\machine.py", line 791, in _run_loop
    report_crash(self._exception['exception'], "exception_during_run", self.config)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\crash_reporter.py", line 236, in report_crash
    response = input("Do you want to report the crash to the MPF team (yes/no/show)? ")
EOFError
