2025-10-15 17:36:08,972 : INFO : root : Loading config.
2025-10-15 17:36:08,978 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2025-10-15 17:36:08,979 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\f7776651e259183bd84a8c8d686bf868.mpf_cache
2025-10-15 17:36:09,088 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\richa\ttp7\modes\attract\config\attract.yaml
2025-10-15 17:36:09,089 : INFO : ConfigProcessor : Loading config from file C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\modes\attract\config\attract.yaml.
2025-10-15 17:36:09,090 : INFO : ConfigProcessor : Loading config: C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\modes\attract\config\attract.yaml
2025-10-15 17:36:09,090 : INFO : ConfigProcessor : Loading config from file C:\Users\richa\ttp7\modes\attract\config\attract.yaml.
2025-10-15 17:36:09,098 : INFO : ConfigProcessor : Loading config: C:\Users\richa\ttp7\modes\attract\config\attract.yaml
2025-10-15 17:36:09,099 : INFO : ConfigProcessor : Config file cache created: C:\Users\richa\AppData\Local\Temp\70233839fc0b792ce11a62f3c18c1950.mpf_cache
2025-10-15 17:36:09,100 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\9c8dea79ca4d15ee886340e992e8cb9d.mpf_cache
2025-10-15 17:36:09,100 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\67a19b095f918111543419ac0271bfb1.mpf_cache
2025-10-15 17:36:09,101 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\be387b0e8ed00556ec738d83cd6947d1.mpf_cache
2025-10-15 17:36:09,102 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\5a8efabd9666d8c71fa755fc28a9bf1e.mpf_cache
2025-10-15 17:36:09,103 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\fb58745e58584e219ff53db445e8e9f2.mpf_cache
2025-10-15 17:36:09,103 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\3a5badf48d988f9fc0f9b093a934917d.mpf_cache
2025-10-15 17:36:09,104 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\9e788d9ac28f3464b985b20edf80a10e.mpf_cache
2025-10-15 17:36:09,105 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\7e426d8ffa907371bf962f3181d8bdf2.mpf_cache
2025-10-15 17:36:09,106 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\b710dc01437f1dfd05f3b5275f67493b.mpf_cache
2025-10-15 17:36:09,107 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\0a23590f4081187a3ecee75c7657616e.mpf_cache
2025-10-15 17:36:09,107 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\374a5edaf0766cb9005f368df852c09d.mpf_cache
2025-10-15 17:36:09,108 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\b50d1c72289d6f8f00cba34766fbb2e5.mpf_cache
2025-10-15 17:36:09,109 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\bfc680b70531e398658191c2a179bce0.mpf_cache
2025-10-15 17:36:09,110 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\069a726c379c7a3dc006889318eb30f2.mpf_cache
2025-10-15 17:36:09,110 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\6159dd3e8b071f5aa615e717784124e9.mpf_cache
2025-10-15 17:36:09,111 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\e382c4765158d2be92c1673fc03a4ad6.mpf_cache
2025-10-15 17:36:09,112 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\868b3b6361e3aaa0a56bd50d9388247e.mpf_cache
2025-10-15 17:36:09,112 : INFO : Machine : Mission Pinball Framework Core Engine v0.57.0.dev39
2025-10-15 17:36:09,112 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2025-10-15-17-36-08-mpf-DESKTOP-RK7BE5M.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2025-10-15 17:36:09,112 : INFO : Machine : MPF path: C:\Users\richa\mpfvirtual4\lib\site-packages\mpf
2025-10-15 17:36:09,112 : INFO : Machine : Machine path: C:\Users\richa\ttp7
2025-10-15 17:36:09,112 : INFO : Machine : Platform: win32
2025-10-15 17:36:09,112 : INFO : Machine : Python executable location: C:\Users\richa\mpfvirtual4\Scripts\python.exe
2025-10-15 17:36:09,112 : INFO : Machine : Python version: 3.9.13 (64-bit)
2025-10-15 17:36:09,114 : INFO : Machine : Initializing MPF...
2025-10-15 17:36:09,468 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2025-10-15 17:36:09,530 : INFO : EventManager : Event: ======'machine_var_credit_units'====== Args={'value': 0, 'prev_value': None, 'change': True}
2025-10-15 17:36:09,530 : INFO : EventManager : Event: ======'machine_var_free_play'====== Args={'value': False, 'prev_value': None, 'change': True}
2025-10-15 17:36:09,530 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2025-10-15 17:36:09,530 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 0, 'prev_value': None, 'change': True}
2025-10-15 17:36:09,530 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.57.0.dev39', 'prev_value': None, 'change': True}
2025-10-15 17:36:09,530 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.57.0.dev39, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2025-10-15 17:36:09,530 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.9.13', 'prev_value': None, 'change': True}
2025-10-15 17:36:09,540 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.19045-SP0', 'prev_value': None, 'change': True}
2025-10-15 17:36:09,540 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2025-10-15 17:36:09,540 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2025-10-15 17:36:09,540 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.19045', 'prev_value': None, 'change': True}
2025-10-15 17:36:09,540 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2025-10-15 17:36:09,540 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2025-10-15 17:36:09,580 : INFO : EventManager : Event: ======'drop_target_bank_TIME_up'====== Args={}
2025-10-15 17:36:09,580 : INFO : EventManager : Event: ======'drop_target_bank_TRAVEL_up'====== Args={}
2025-10-15 17:36:09,581 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2025-10-15 17:36:09,581 : INFO : SwitchController : Found active switch: ('2', <Platform.SmartVirtual>) <switch.s_trough1>
2025-10-15 17:36:09,581 : INFO : SwitchController : Found active switch: ('3', <Platform.SmartVirtual>) <switch.s_trough2>
2025-10-15 17:36:09,581 : INFO : SwitchController : Found active switch: ('4', <Platform.SmartVirtual>) <switch.s_trough3>
2025-10-15 17:36:09,581 : INFO : SwitchController : Found active switch: ('5', <Platform.SmartVirtual>) <switch.s_trough4>
2025-10-15 17:36:09,581 : INFO : SwitchController : Found active switch: ('6', <Platform.SmartVirtual>) <switch.s_trough5>
2025-10-15 17:36:09,581 : INFO : SwitchController : Found active switch: ('7', <Platform.SmartVirtual>) <switch.s_trough6>
2025-10-15 17:36:09,586 : ERROR : ConfigValidator : Your config contains a value for the setting "show_player:target", but this is not a valid setting name.
2025-10-15 17:36:09,586 : ERROR : asyncio : Exception in callback EventManager._queue_task_done(<Task finishe...tting name.')>)
handle: <Handle EventManager._queue_task_done(<Task finishe...tting name.')>)>
Traceback (most recent call last):
  File "C:\Users\richa\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 791, in _queue_task_done
    future.result()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 704, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\mode_controller.py", line 97, in initialize_modes
    item.method(config=mode.config[item.config_section],
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_player.py", line 150, in process_mode_config
    config = self.validate_config(config)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_player.py", line 113, in validate_config
    validated_config[event] = self.validate_config_entry(settings, event)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\device_config_player.py", line 56, in validate_config_entry
    raise e
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\device_config_player.py", line 79, in _validate_config_item
    device_settings = self._parse_config(device_settings, device)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_player.py", line 144, in _parse_config
    return self.get_full_config(config)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_player.py", line 216, in get_full_config
    return self.machine.config_validator.validate_config(
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 177, in _validate_config
    self.check_for_invalid_sections(this_spec, source, validation_failure_info)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 336, in check_for_invalid_sections
    raise ConfigFileError('Your config contains a value for the '
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Failed to load config player mode_attract_started:shows with settings {'attract_display_loop': {'target': 'window'}} >> Your config contains a value for the setting "show_player:target", but this is not a valid setting name. Error Code: CFE-ConfigValidator-2 (https://missionpinball.org/logs)
2025-10-15 17:36:09,616 : INFO : Machine : Starting the main run loop.
2025-10-15 17:36:09,623 : INFO : Machine : Shutting down...
2025-10-15 17:36:09,623 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2025-10-15 17:36:10,622 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\machine.py", line 788, in _run_loop
    raise self._exception['exception']
  File "C:\Users\richa\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 791, in _queue_task_done
    future.result()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 704, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\mode_controller.py", line 97, in initialize_modes
    item.method(config=mode.config[item.config_section],
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_player.py", line 150, in process_mode_config
    config = self.validate_config(config)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_player.py", line 113, in validate_config
    validated_config[event] = self.validate_config_entry(settings, event)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\device_config_player.py", line 56, in validate_config_entry
    raise e
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\device_config_player.py", line 79, in _validate_config_item
    device_settings = self._parse_config(device_settings, device)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_player.py", line 144, in _parse_config
    return self.get_full_config(config)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_player.py", line 216, in get_full_config
    return self.machine.config_validator.validate_config(
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 177, in _validate_config
    self.check_for_invalid_sections(this_spec, source, validation_failure_info)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 336, in check_for_invalid_sections
    raise ConfigFileError('Your config contains a value for the '
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Failed to load config player mode_attract_started:shows with settings {'attract_display_loop': {'target': 'window'}} >> Your config contains a value for the setting "show_player:target", but this is not a valid setting name. Error Code: CFE-ConfigValidator-2 (https://missionpinball.org/logs)
2025-10-15 17:36:20,456 : ERROR : root : 
Traceback (most recent call last):
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\machine.py", line 788, in _run_loop
    raise self._exception['exception']
  File "C:\Users\richa\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 791, in _queue_task_done
    future.result()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 704, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\mode_controller.py", line 97, in initialize_modes
    item.method(config=mode.config[item.config_section],
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_player.py", line 150, in process_mode_config
    config = self.validate_config(config)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_player.py", line 113, in validate_config
    validated_config[event] = self.validate_config_entry(settings, event)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\device_config_player.py", line 56, in validate_config_entry
    raise e
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\device_config_player.py", line 79, in _validate_config_item
    device_settings = self._parse_config(device_settings, device)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_player.py", line 144, in _parse_config
    return self.get_full_config(config)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_player.py", line 216, in get_full_config
    return self.machine.config_validator.validate_config(
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 177, in _validate_config
    self.check_for_invalid_sections(this_spec, source, validation_failure_info)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 336, in check_for_invalid_sections
    raise ConfigFileError('Your config contains a value for the '
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Failed to load config player mode_attract_started:shows with settings {'attract_display_loop': {'target': 'window'}} >> Your config contains a value for the setting "show_player:target", but this is not a valid setting name. Error Code: CFE-ConfigValidator-2 (https://missionpinball.org/logs)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\commands\game.py", line 236, in __init__
    self.machine.run()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\machine.py", line 684, in run
    self._run_loop()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\machine.py", line 791, in _run_loop
    report_crash(self._exception['exception'], "exception_during_run", self.config)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\crash_reporter.py", line 236, in report_crash
    response = input("Do you want to report the crash to the MPF team (yes/no/show)? ")
EOFError
