2025-10-08 18:52:56,688 : INFO : root : Loading config.
2025-10-08 18:52:56,692 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2025-10-08 18:52:56,693 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\f7776651e259183bd84a8c8d686bf868.mpf_cache
2025-10-08 18:52:56,778 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\70233839fc0b792ce11a62f3c18c1950.mpf_cache
2025-10-08 18:52:56,778 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\9c8dea79ca4d15ee886340e992e8cb9d.mpf_cache
2025-10-08 18:52:56,779 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\richa\ttp7\modes\base\config\base.yaml
2025-10-08 18:52:56,779 : INFO : ConfigProcessor : Loading config from file C:\Users\richa\ttp7\modes\base\config\base.yaml.
2025-10-08 18:52:56,791 : INFO : ConfigProcessor : Loading config: C:\Users\richa\ttp7\modes\base\config\base.yaml
2025-10-08 18:52:56,792 : INFO : ConfigProcessor : Config file cache created: C:\Users\richa\AppData\Local\Temp\67a19b095f918111543419ac0271bfb1.mpf_cache
2025-10-08 18:52:56,793 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\be387b0e8ed00556ec738d83cd6947d1.mpf_cache
2025-10-08 18:52:56,794 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\b710dc01437f1dfd05f3b5275f67493b.mpf_cache
2025-10-08 18:52:56,795 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\0a23590f4081187a3ecee75c7657616e.mpf_cache
2025-10-08 18:52:56,796 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\374a5edaf0766cb9005f368df852c09d.mpf_cache
2025-10-08 18:52:56,796 : INFO : Machine : Mission Pinball Framework Core Engine v0.57.0.dev39
2025-10-08 18:52:56,796 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2025-10-08-18-52-56-mpf-DESKTOP-RK7BE5M.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2025-10-08 18:52:56,797 : INFO : Machine : MPF path: C:\Users\richa\mpfvirtual4\lib\site-packages\mpf
2025-10-08 18:52:56,797 : INFO : Machine : Machine path: C:\Users\richa\ttp7
2025-10-08 18:52:56,797 : INFO : Machine : Platform: win32
2025-10-08 18:52:56,797 : INFO : Machine : Python executable location: C:\Users\richa\mpfvirtual4\Scripts\python.exe
2025-10-08 18:52:56,797 : INFO : Machine : Python version: 3.9.13 (64-bit)
2025-10-08 18:52:56,799 : INFO : Machine : Initializing MPF...
2025-10-08 18:52:57,133 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2025-10-08 18:52:57,188 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2025-10-08 18:52:57,188 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 2008600, 'prev_value': None, 'change': True}
2025-10-08 18:52:57,188 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.57.0.dev39', 'prev_value': None, 'change': True}
2025-10-08 18:52:57,188 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.57.0.dev39, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2025-10-08 18:52:57,188 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.9.13', 'prev_value': None, 'change': True}
2025-10-08 18:52:57,198 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.19045-SP0', 'prev_value': None, 'change': True}
2025-10-08 18:52:57,198 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2025-10-08 18:52:57,198 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2025-10-08 18:52:57,198 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.19045', 'prev_value': None, 'change': True}
2025-10-08 18:52:57,198 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2025-10-08 18:52:57,198 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2025-10-08 18:52:57,225 : ERROR : ConfigValidator : Your config contains a value for the setting "mode:base:shots:right_scoop_shot:enable_event", but this is not a valid setting name.
2025-10-08 18:52:57,226 : ERROR : asyncio : Exception in callback EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...tting name.')>) at C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py:124
handle: <Handle EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...tting name.')>) at C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py:124>
Traceback (most recent call last):
  File "C:\Users\richa\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 127, in _async_handler_done
    future.result()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\device_manager.py", line 89, in _load_device_modules
    await self.machine.mode_controller.load_mode_devices()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\mode_controller.py", line 86, in load_mode_devices
    await mode.load_mode_devices()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\mode.py", line 438, in load_mode_devices
    settings = device.validate_and_parse_config(settings, True, "mode:" + self.name)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\devices\shot.py", line 72, in validate_and_parse_config
    config = super().validate_and_parse_config(config, is_mode_config, debug_prefix)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\device.py", line 108, in validate_and_parse_config
    self.machine.config_validator.validate_config(
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 177, in _validate_config
    self.check_for_invalid_sections(this_spec, source, validation_failure_info)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 336, in check_for_invalid_sections
    raise ConfigFileError('Your config contains a value for the '
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Your config contains a value for the setting "mode:base:shots:right_scoop_shot:enable_event", but this is not a valid setting name. Error Code: CFE-ConfigValidator-2 (https://missionpinball.org/logs)
2025-10-08 18:52:57,241 : INFO : Machine : Starting the main run loop.
2025-10-08 18:52:57,246 : INFO : Machine : Shutting down...
2025-10-08 18:52:57,246 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2025-10-08 18:52:58,241 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\machine.py", line 788, in _run_loop
    raise self._exception['exception']
  File "C:\Users\richa\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 127, in _async_handler_done
    future.result()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\device_manager.py", line 89, in _load_device_modules
    await self.machine.mode_controller.load_mode_devices()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\mode_controller.py", line 86, in load_mode_devices
    await mode.load_mode_devices()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\mode.py", line 438, in load_mode_devices
    settings = device.validate_and_parse_config(settings, True, "mode:" + self.name)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\devices\shot.py", line 72, in validate_and_parse_config
    config = super().validate_and_parse_config(config, is_mode_config, debug_prefix)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\device.py", line 108, in validate_and_parse_config
    self.machine.config_validator.validate_config(
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 177, in _validate_config
    self.check_for_invalid_sections(this_spec, source, validation_failure_info)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 336, in check_for_invalid_sections
    raise ConfigFileError('Your config contains a value for the '
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Your config contains a value for the setting "mode:base:shots:right_scoop_shot:enable_event", but this is not a valid setting name. Error Code: CFE-ConfigValidator-2 (https://missionpinball.org/logs)
2025-10-08 18:53:10,187 : ERROR : root : 
Traceback (most recent call last):
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\machine.py", line 788, in _run_loop
    raise self._exception['exception']
  File "C:\Users\richa\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 127, in _async_handler_done
    future.result()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\device_manager.py", line 89, in _load_device_modules
    await self.machine.mode_controller.load_mode_devices()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\mode_controller.py", line 86, in load_mode_devices
    await mode.load_mode_devices()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\mode.py", line 438, in load_mode_devices
    settings = device.validate_and_parse_config(settings, True, "mode:" + self.name)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\devices\shot.py", line 72, in validate_and_parse_config
    config = super().validate_and_parse_config(config, is_mode_config, debug_prefix)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\device.py", line 108, in validate_and_parse_config
    self.machine.config_validator.validate_config(
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 177, in _validate_config
    self.check_for_invalid_sections(this_spec, source, validation_failure_info)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 336, in check_for_invalid_sections
    raise ConfigFileError('Your config contains a value for the '
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Your config contains a value for the setting "mode:base:shots:right_scoop_shot:enable_event", but this is not a valid setting name. Error Code: CFE-ConfigValidator-2 (https://missionpinball.org/logs)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\commands\game.py", line 236, in __init__
    self.machine.run()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\machine.py", line 684, in run
    self._run_loop()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\machine.py", line 791, in _run_loop
    report_crash(self._exception['exception'], "exception_during_run", self.config)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\crash_reporter.py", line 236, in report_crash
    response = input("Do you want to report the crash to the MPF team (yes/no/show)? ")
EOFError
