2025-10-05 14:32:17,922 : INFO : root : Loading config.
2025-10-05 14:32:17,926 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2025-10-05 14:32:17,927 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\bad76953a596b8c99f832e0e98026c3b.mpf_cache
2025-10-05 14:32:18,016 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\77a998d318c788df5647a1900cedfc56.mpf_cache
2025-10-05 14:32:18,017 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\9c8dea79ca4d15ee886340e992e8cb9d.mpf_cache
2025-10-05 14:32:18,018 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\richa\ttp5\modes\base\config\base.yaml
2025-10-05 14:32:18,018 : INFO : ConfigProcessor : Loading config from file C:\Users\richa\ttp5\modes\base\config\base.yaml.
2025-10-05 14:32:18,031 : INFO : ConfigProcessor : Loading config: C:\Users\richa\ttp5\modes\base\config\base.yaml
2025-10-05 14:32:18,032 : INFO : ConfigProcessor : Config file cache created: C:\Users\richa\AppData\Local\Temp\8ddee2e87a4f178751335e99da00e9c4.mpf_cache
2025-10-05 14:32:18,033 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\16d594341c3fbe91b1b6d496c05a6fb0.mpf_cache
2025-10-05 14:32:18,034 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\9ea1b14cb2b1cce5e8bf981a1ff8cfc5.mpf_cache
2025-10-05 14:32:18,034 : INFO : ConfigProcessor : Loading config from cache: C:\Users\richa\AppData\Local\Temp\6cbce11faef0ddcfeddb2a5b8dbeb4ae.mpf_cache
2025-10-05 14:32:18,035 : INFO : Machine : Mission Pinball Framework Core Engine v0.57.0.dev39
2025-10-05 14:32:18,035 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2025-10-05-14-32-17-mpf-DESKTOP-RK7BE5M.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2025-10-05 14:32:18,035 : INFO : Machine : MPF path: C:\Users\richa\mpfvirtual4\lib\site-packages\mpf
2025-10-05 14:32:18,035 : INFO : Machine : Machine path: C:\Users\richa\ttp5
2025-10-05 14:32:18,035 : INFO : Machine : Platform: win32
2025-10-05 14:32:18,035 : INFO : Machine : Python executable location: C:\Users\richa\mpfvirtual4\Scripts\python.exe
2025-10-05 14:32:18,035 : INFO : Machine : Python version: 3.9.13 (64-bit)
2025-10-05 14:32:18,037 : INFO : Machine : Initializing MPF...
2025-10-05 14:32:18,677 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2025-10-05 14:32:18,732 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2025-10-05 14:32:18,733 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 7584, 'prev_value': None, 'change': True}
2025-10-05 14:32:18,733 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.57.0.dev39', 'prev_value': None, 'change': True}
2025-10-05 14:32:18,733 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.57.0.dev39, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2025-10-05 14:32:18,733 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.9.13', 'prev_value': None, 'change': True}
2025-10-05 14:32:18,744 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.19045-SP0', 'prev_value': None, 'change': True}
2025-10-05 14:32:18,744 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2025-10-05 14:32:18,744 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2025-10-05 14:32:18,744 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.19045', 'prev_value': None, 'change': True}
2025-10-05 14:32:18,744 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2025-10-05 14:32:18,744 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2025-10-05 14:32:18,771 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2025-10-05 14:32:18,771 : INFO : SwitchController : Found active switch: ('2', <Platform.SmartVirtual>) <switch.s_trough1>
2025-10-05 14:32:18,772 : INFO : SwitchController : Found active switch: ('3', <Platform.SmartVirtual>) <switch.s_trough2>
2025-10-05 14:32:18,772 : INFO : SwitchController : Found active switch: ('4', <Platform.SmartVirtual>) <switch.s_trough3>
2025-10-05 14:32:18,772 : INFO : SwitchController : Found active switch: ('5', <Platform.SmartVirtual>) <switch.s_trough4>
2025-10-05 14:32:18,772 : INFO : SwitchController : Found active switch: ('6', <Platform.SmartVirtual>) <switch.s_trough5>
2025-10-05 14:32:18,772 : INFO : SwitchController : Found active switch: ('7', <Platform.SmartVirtual>) <switch.s_trough6>
2025-10-05 14:32:18,773 : ERROR : asyncio : Exception in callback EventManager._queue_task_done(<Task finishe...ss \'int\'>')>)
handle: <Handle EventManager._queue_task_done(<Task finishe...ss \'int\'>')>)>
Traceback (most recent call last):
  File "C:\Users\richa\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 791, in _queue_task_done
    future.result()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 704, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\mode_controller.py", line 97, in initialize_modes
    item.method(config=mode.config[item.config_section],
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_player.py", line 150, in process_mode_config
    config = self.validate_config(config)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_player.py", line 113, in validate_config
    validated_config[event] = self.validate_config_entry(settings, event)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\event_player.py", line 75, in validate_config_entry
    config = super().validate_config_entry(settings, name)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\flat_config_player.py", line 17, in validate_config_entry
    config = self._parse_config(settings, name)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_player.py", line 144, in _parse_config
    return self.get_full_config(config)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\flat_config_player.py", line 23, in get_full_config
    value[element] = super().get_full_config(value[element])
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_player.py", line 216, in get_full_config
    return self.machine.config_validator.validate_config(
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 182, in _validate_config
    self.validation_error(source, validation_failure_info, "Config attribute should be dict but is {}".format(
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 700, in validation_error
    raise ConfigFileError("Config validation error: Entry {} = \"{}\" is not valid. {}".format(
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry event_player:event_player = "777777" is not valid. Config attribute should be dict but is <class 'int'> Error Code: CFE-ConfigValidator-5 (https://missionpinball.org/logs)
2025-10-05 14:32:18,806 : INFO : Machine : Starting the main run loop.
2025-10-05 14:32:18,815 : INFO : Machine : Shutting down...
2025-10-05 14:32:18,816 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2025-10-05 14:32:19,831 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\machine.py", line 788, in _run_loop
    raise self._exception['exception']
  File "C:\Users\richa\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 791, in _queue_task_done
    future.result()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 704, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\mode_controller.py", line 97, in initialize_modes
    item.method(config=mode.config[item.config_section],
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_player.py", line 150, in process_mode_config
    config = self.validate_config(config)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_player.py", line 113, in validate_config
    validated_config[event] = self.validate_config_entry(settings, event)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\event_player.py", line 75, in validate_config_entry
    config = super().validate_config_entry(settings, name)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\flat_config_player.py", line 17, in validate_config_entry
    config = self._parse_config(settings, name)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_player.py", line 144, in _parse_config
    return self.get_full_config(config)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\flat_config_player.py", line 23, in get_full_config
    value[element] = super().get_full_config(value[element])
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_player.py", line 216, in get_full_config
    return self.machine.config_validator.validate_config(
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 182, in _validate_config
    self.validation_error(source, validation_failure_info, "Config attribute should be dict but is {}".format(
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 700, in validation_error
    raise ConfigFileError("Config validation error: Entry {} = \"{}\" is not valid. {}".format(
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry event_player:event_player = "777777" is not valid. Config attribute should be dict but is <class 'int'> Error Code: CFE-ConfigValidator-5 (https://missionpinball.org/logs)
2025-10-05 14:32:52,149 : ERROR : root : 
Traceback (most recent call last):
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\machine.py", line 788, in _run_loop
    raise self._exception['exception']
  File "C:\Users\richa\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 791, in _queue_task_done
    future.result()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\events.py", line 704, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\mode_controller.py", line 97, in initialize_modes
    item.method(config=mode.config[item.config_section],
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_player.py", line 150, in process_mode_config
    config = self.validate_config(config)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_player.py", line 113, in validate_config
    validated_config[event] = self.validate_config_entry(settings, event)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\event_player.py", line 75, in validate_config_entry
    config = super().validate_config_entry(settings, name)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\flat_config_player.py", line 17, in validate_config_entry
    config = self._parse_config(settings, name)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_player.py", line 144, in _parse_config
    return self.get_full_config(config)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\config_players\flat_config_player.py", line 23, in get_full_config
    value[element] = super().get_full_config(value[element])
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_player.py", line 216, in get_full_config
    return self.machine.config_validator.validate_config(
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 182, in _validate_config
    self.validation_error(source, validation_failure_info, "Config attribute should be dict but is {}".format(
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\config_validator.py", line 700, in validation_error
    raise ConfigFileError("Config validation error: Entry {} = \"{}\" is not valid. {}".format(
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry event_player:event_player = "777777" is not valid. Config attribute should be dict but is <class 'int'> Error Code: CFE-ConfigValidator-5 (https://missionpinball.org/logs)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\commands\game.py", line 236, in __init__
    self.machine.run()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\machine.py", line 684, in run
    self._run_loop()
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\machine.py", line 791, in _run_loop
    report_crash(self._exception['exception'], "exception_during_run", self.config)
  File "C:\Users\richa\mpfvirtual4\lib\site-packages\mpf\core\crash_reporter.py", line 236, in report_crash
    response = input("Do you want to report the crash to the MPF team (yes/no/show)? ")
EOFError
